### ISSUE TITLE
Improving the terminal output 

### ISSUE THREAD

**Issue by abdimk** [Chapa-Et/chapa-cli#3]
i really want to improve the terminal output instead of using simple print function what if we make a table for every repeated outputs like this and this will be implemented for the rest and i also formatted the **created-at** and the **updated at** 

also i can't test the functionality of those commands

chapa transaction verify --reference REF123
chapa transaction events AP9ARo9XvMO5

with demo account which makes it challenging for me to test things out 

![Screenshot from 2024-08-14 15-59-22](https://github.com/user-attachments/assets/bf4704f0-82cb-40a9-ab85-32ab05ff1cec)

**Comment by isrugeek** [comment]
Hi @abdimk 

Thank you for your efforts in improving the terminal output; both using a table for repeated outputs, and formatting the `dates fields` will definitely enhance clarity.

Regarding testing the `transaction verify` and `transaction events` commands with a demo account, I understand the challenge. Please send an email to **_myfirstname [at] mycompany domain_**, so we can provide you with access to a live account for thorough testing. 

Also, when you're ready, submit a pull request on GitHub, and one of our developers will review it properly.

Cheers

**Comment by abdimk** [comment]
Thank you for providing me the credentials it helped me alot there are some major changes i did i will immediately open pull request after i finished 


https://github.com/user-attachments/assets/f5715e52-50c6-4a7b-a08a-43f4924132ff

**Comment by abdimk** [comment]
**New features**  

_realtime rate exchange_ and _best transaction for of the day_ from https://banksethiopia.com/ethiopian-birr-exchange-rate/ website i actually manage to impliment it but insted of scraping the website what if we have an api and a database that will be updated by the github workflow(CD/CI) and the cli will sent the request to the database instead of every user parsing the html content. i will be responsible for the scraping stuff but give you the api (so it will be clear and legal on your side) 

Or we  just can Drop the feature and fix the docs 

![Screenshot from 2024-08-19 16-44-46](https://github.com/user-attachments/assets/302991de-9ce0-4d1e-9084-555d796e6e27)
![Screenshot from 2024-08-19 16-41-51](https://github.com/user-attachments/assets/93b9f6a7-2b52-4312-a344-86be00cdaa9c)

**Comment by isrugeek** [comment]
Hi @abdimk 

Cool idea, but the better way to do this is maybe using an API instead of scrapping, but I don't also see the use of this feature tho.
